# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bigfun

on:
  workflow_dispatch:
  schedule:
     - cron: '0 8,16 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      Bfurl: ${{ secrets.Bfurl }}
      Bfurl1: ${{ secrets.Bfurl1 }}
      Bfurl2: ${{ secrets.Bfurl2 }}
      Bfurl3: ${{ secrets.Bfurl3 }}
      Bfurl4: ${{ secrets.Bfurl4 }}
      Bfurl5: ${{ secrets.Bfurl5 }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.Bfurl
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【bigfun】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl }}
          Bfhd: ${{ secrets.Bfhd }}
          Bfbody: ${{ secrets.Bfbody }}
                        
      - name: '运行 【bigfun1】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl1 }}
          Bfhd: ${{ secrets.Bfhd1 }}
          Bfbody: ${{ secrets.Bfbody1 }} 
                 
      - name: '运行 【bigfun2】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl2 }}
          Bfhd: ${{ secrets.Bfhd2 }}
          Bfbody: ${{ secrets.Bfbody2 }}
                 
      - name: '运行 【bigfun3】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl3 }}
          Bfhd: ${{ secrets.Bfhd3 }}
          Bfbody: ${{ secrets.Bfbody3 }}         


      - name: '运行 【bigfun4】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl4 }}
          Bfhd: ${{ secrets.Bfhd4 }}
          Bfbody: ${{ secrets.Bfbody4 }}
          
          
