# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: BBB2

on:
  workflow_dispatch:
  # 账号越多文章越多，运行一次消耗的时间也越长，文章和视频不要一块运行，cron自己看着写
  schedule:
     - cron: '0 7-23/2 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      BBB_ck: ${{ secrets.BBB_ck }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.BBB_ck
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【BBB】'
        if: env.BBB_ck         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck }}
          
      - name: '运行 【BBB1】'
        if: env.BBB_ck1         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck1 }}
          
      - name: '运行 【BBB2】'
        if: env.BBB_ck2         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck2 }}
          
      - name: '运行 【BBB3】'
        if: env.BBB_ck3         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck3 }}
          
      - name: '运行 【BBB4】'
        if: env.BBB_ck4         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck4 }}
          
      - name: '运行 【BBB5】'
        if: env.BBB_ck         
        run: |
          cd ~/Scripts
          node Task/BBB.js
        env:
          BBB_ck: ${{ secrets.BBB_ck5 }}


