# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bigfun

on:
  workflow_dispatch:
  schedule:
     - cron: '0 8,16 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      Bfurl: ${{ secrets.Bfurl }}
      Bfurl1: ${{ secrets.Bfurl1 }}
      Bfurl2: ${{ secrets.Bfurl2 }}
      Bfurl3: ${{ secrets.Bfurl3 }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.Bfurl
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【bigfun】'
        if: env.Bfurl         
        run: |
          cd ~/Scripts
          node Task/bigfun.js
        env:
          Bfurl: ${{ secrets.Bfurl }}
          Bfhd: ${{ secrets.Bfhd }}
          Bfbody: ${{ secrets.Bfbody }}
          

