# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: jrtt

on:
  workflow_dispatch:
  schedule:
     - cron: '*/12 * * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        JRTTSIGNURL: ${{ secrets.JRTTSIGNURL }}
        JRTTSIGNKEY: ${{ secrets.JRTTSIGNKEY }}
        JRTTFARMURL: ${{ secrets.JRTTFARMURL }}
        JRTTFARMKEY: ${{ secrets.JRTTFARMKEY }}
        JRTTREADURL: ${{ secrets.JRTTREADURL }}
        JRTTREADKEY: ${{ secrets.JRTTREADKEY }}
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.JRTTSIGNURL
        run: |
          npm install
      - name: '运行 【jrtt】'
        if: env.JRTTSIGNURL
        run: |
          node Task/jrtt.js
        env:
          YOUTH_NOTIFY_CONTROL: ${{ secrets.YOUTH_NOTIFY_CONTROL }}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
