
name: xp_adwktt

on:
  workflow_dispatch:
  schedule:
     - cron: '0 7-23/2 * * *'
  watch:
    types: started
env:
  TZ: Asia/Shanghai

jobs:
  build:
    env:
      xpCookie: ${{ secrets.xpCookie }}
      BBB_CK1: ${{ secrets.BBB_CK1 }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      BARK_PUSH: ${{ secrets.BARK_PUSH }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      BARK_SOUND: ${{ secrets.BARK_SOUND }}
      DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
      DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
      
      
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.xpCookie
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
                 
      - name: '运行 【xp_adwktt】'
        if: env.xpCookie         
        run: |
          cd ~/Scripts
          node Task/xp_adwktt.js
        env:
          xpCookie: ${{ secrets.xpCookie }}
          

